config/routes.rb
Screenplay::Application.routes.draw do
  root 'movies#index'

  resources :movies
  resources :televisions

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	validates :movie, :presence => true, :length => {:maximum => 200, :minimum => 2}
	validates :actors, :presence => true, :length => {:maximum => 1500, :minimum => 4}
	validates :director, :presence => true, :length => {:maximum => 100, :minimum => 2}
	validates :description, :presence => true, :length => {:maximum => 2000, :minimum => 2}
end

app/models/television.rb
class Television < ActiveRecord::Base
	validates :title, :presence => true, :length => {:maximum => 300, :minimum => 3}
	validates :actors, :presence => true
	validates :genres, :presence => true
	validates :channels, :presence => true
	validates :description, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def index
		@movie = Movie.order("RANDOM()").first
	end

	def create
		@movie = Movie.create(movie_params)
		if @movie.invalid?
			flash[:error] = 'Could not enter the data in. Please, enter all the missing data.'
		end
		redirect_to root_path
	end

	def show
	end

	private

	def movie_params
		params.require(:movie).permit(:movie, :actors, :director, :description)
	end
end

app/controllers/televisions_controller.rb
class TelevisionsController < ApplicationController

	def index
		@television = Television.order("RANDOM()").first(params[:television_id])
	end

	def new
		@television = Television.new
	end

	def create
		@television = Television.create(quote_params)
		if @television.invalid?
			flash[:error] = "<strong>The data was invalid.<strong>Reenter the data."
		end
		redirect_to televisions_path
	end

	private

	def quote_params
		params.require(:television).permit(:title, :actors, :genres, :channels, :description)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/televisions_helper.rb
module TelevisionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Screenplay</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<div class="col-xs-1">
			<%= link_to root_path do %>
			<div class="rectangle">
				<h4 class="logo-title">Movies</h4>
			</div>
		</div>
    <div class="col-xs-1">
      <%= link_to televisions_path do %>
      <div class="rectangle">
        <h4 class="second-logo-title">TV Shows</h4>
      </div>
    </div>
    <% end %>
		<div class="col-xs-5 description">
			Add movies and TV shows here whether it was great or awful or in-between!
		</div>
		<div class="col-xs-5 links">
<!-- Button trigger modal -->
      <%= link_to 'Add movies here', '#', :data => {:toggle => 'modal', :target => '#myModal'} %>
      <%= link_to 'Add TV shows here', new_television_path %>
		</div>
    <% end %>
	</header>


<!-- Modal -->
  	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    	<div class="modal-dialog">
      		<div class="modal-content">
        		<div class="modal-header">
          			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          			<h4 class="modal-title" id="myModalLabel">Add any movies here</h4>
        		</div>
        	
            <%= simple_form_for Movie.new do |x| %>
            <div class="modal-body">
              <%= x.input :movie, :placeholder => "Cast Away" %>
              <br />
              <%= x.input :actors,:placeholder => "Clint Eastwood, Tom Hanks, Emma Watson" %>
              <br />
              <%= x.input :director, :placeholder => "Martin Scorsese" %>
              <br />
              <%= x.input :description, :placeholder => "Best movie ever, great acting too." %>
              <br /> <br />
              
            </div>
        	<div class="modal-footer">
          		<%= x.submit 'Create', :class => "btn btn-success" %>
              <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        	</div>
          <% end %>
      	</div>
    	</div>
  	</div>

	<hr />
	<br class="clear" />

	<div class="container">	
		<% if flash[:error].present? %>
			<div class="col-xs-10 col-xs-offset-1 alert alert-danger">
				<%= flash[:error].html_safe %>
			</div>
		<% end %>
		<%= yield %>
	</div>

	<div class="footer">
    	<div class="container">
    		<div class="col-xs-6 footer-links">
    			<a href="http://www.imdb.com" class="footer-links">This is a great website to read about movies!</a><br />
    			<a href="http://www.rottentomatoes.com" class="footer-links">Another great movie website!</a>
      		</div>
      		<div class="col-xs-6">
      			<p class="text-muted">Website created by Alan<br />
      			&copy; 2015</p>
      		</div>
    	</div>
  	</div>

</body>
</html>

app/views/movies/index.html.erb
<h1 class="movie"><%= @movie.movie %></h1>
<h2>Actors: <%= @movie.actors %></h2>
<h2>Director(s): <%= @movie.director %></h2>
<h3>Description of the movie: <%= @movie.description %></h3>

app/views/televisions/index.html.erb
<h1 class="text-center shows"><%= @television.title %></h1>
<div class="box">
	<h2>Actors: <%= @television.actors %></h2>
	<h3>Description: <%= @television.description %></h3>
	<h4>Genre(s): <%= @television.genres %></h4>
	<h4>Channel(s): <%= @television.channels %></h4>
</div>

app/views/televisions/new.html.erb
<h1>Enter any tv shows</h1>
<%= simple_form_for @television do |f| %>
	<%= f.input :title, :placeholder => 'Mad Men' %>
	<%= f.input :actors, :placeholder => 'Jon Hamm, Elisabeth Moss' %>
	<%= f.input :genres, :placeholder => 'Period Drama' %>
	<%= f.input :channels, :placeholder => 'AMC' %>
	<%= f.input :description, :placeholder => 'About business in the 1960\'s' %>
	<br /><br />
	<%= f.submit 'Create', :class => 'btn btn-success' %>
<% end %>